routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    //return view('welcome');
    return view('utama.main');
});*/

Route::get('/test', function () {
    
    return view('adminpage.message.template_reply');
});

Route::get('/step', function () {
    
    return view('mo.test');
});

Route::get('/step2', function () {
    
    return view('mo.test2');
});

Route::get('/', 'Utama\UtamaController@index');
Route::post('praaplication/store', 'Praaplication\PraaplicationController@store');
Route::get('praapplication/{id}', 'Praaplication\PraaplicationController@kira');
Route::post('praapplication/just_calculate', 'Praaplication\PraaplicationController@just_calculate');

Route::resource('cif', 'CifController');

Route::get('/hidden', 'Utama\UtamaController@hidden');

Route::get('about', 'Utama\UtamaController@about');
Route::get('service', 'Utama\UtamaController@service');
Route::get('faq', 'Utama\UtamaController@faq');
Route::get('contact', 'Utama\UtamaController@contact');
//Route::post('/praaplication/save', 'Praaplication\PraaplicationController@save_praaplication');

Route::resource('message', 'Utama\MessageController');
Route::get('/reply-que/{id}', 'Utama\MessageController@show');
Route::post('/reply_post', 'Utama\MessageController@update');

Route::resource('praaplication', 'Praaplication\PraaplicationController');

Route::post('/praaplication/kelayakan', 'Praaplication\PraaplicationController@kelayakan');
Route::get('/praaplication/upload-file/{id}', 'Praaplication\PraaplicationController@upload');
Route::post('/praaplication/upload-file/uploads/{id}', 'Praaplication\PraaplicationController@uploads');
Route::post('/praaplication/finish', 'Praaplication\PraaplicationController@finish');
Route::get('upload-praaplication', 'Praaplication\PraaplicationController@upload');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/adminnew', 'AdminNewController@index')->name('adminnew');


Route::group( ['middleware' => ['auth']], function() {

    Route::resource('test', 'TestController');
    Route::resource('mo', 'MOController');
    Route::get('/add_leader/{id}', 'MOController@add_leader');
    Route::post('/mo/add_leader', 'MOController@post_leader'); 
    Route::get('/mo/update1/{id}', 'MOController@updatestatus1'); 
    Route::get('/mo/update2/{id}', 'MOController@updatestatus2');
    Route::get('/add_manager/{id}', 'MOController@add_manager');
    Route::post('/mo/add_manager', 'MOController@post_manager'); 
    

    Route::resource('users', 'UserController');
    Route::get('/users/edit/{id}', 'UserController@edit');
    Route::delete('/users/destroy/{id}', 'UserController@destroy');
    Route::resource('stage', 'StageController');
    Route::resource('profile1', 'ProfileController');
    Route::post('/save/profile/{id}', 'ProfileController@store_profile');
    Route::post('/save/background/{id}', 'ProfileController@store_background');
    Route::resource('cus_mo', 'CustomerMoController');
    
    Route::post('/profileupdate', 'ProfileController@update');
    

    Route::get('/userdata/update/{id}', 'UserController@updatestatus'); 
    Route::get('/userdata/update1/{id}', 'UserController@updatestatus1'); 
    Route::post('/users/status/{id}', 'UserController@status'); //tes
    
    Route::resource('roles', 'RoleController');
    Route::resource('loan', 'LoanController');
    
    Route::get('/location/show/{id}', 'AdminNewController@view_location');
    Route::get('/history/show/{id}', 'AdminNewController@view_history');
    Route::get('/doc/show/{cus_id}', 'AdminNewController@view_doc');
    Route::get('/doc/submit/{id}', 'AdminNewController@submit_doc_cus');
    Route::post('/doc/submit/uploads/{id}', 'AdminNewController@uploads');

    //view form
    Route::get('/view_form/{id}/first_step', 'ViewController@first_step');
    Route::get('/view_form/{id}/second_step', 'ViewController@second_step');
    Route::get('/view_form/{id}/fourth_step', 'ViewController@fourth_step');

    //Processor 1
    Route::get('/assess_addcus_X', 'AssessmentController@create'); //hidden add cus lama
    Route::get('/assess_addcus', 'POneController@create');
    Route::post('/processor1/addcus', 'POneController@store');
    Route::get('/cus/add/{id}', 'PMOController@form_upload');
    Route::get('/doc/spekar/{id}', 'AdminNewController@submit_verify');
    Route::get('/speakar/doc/{id}', 'AssessmentController@kira');
    Route::post('/oassessment/kira/uploads/{id}', 'AssessmentController@uploads');
    Route::post('/save/spekar/{id}', 'LoanEliController@store');
    Route::get('/doc/spekardown/{cus_id}', 'LoanEliController@show');
    Route::post('/routeto/user/{id}', 'LoanEliController@routeto');
    Route::post('/send_spekar', 'LoanEliController@spekar_routeto');
    Route::get('/uploadspekar_p1', 'POneController@uploadspekar_p1');
    Route::get('/route_to_mo', 'POneController@route_to_mo');
    Route::post('/iclocreject/{id}', 'POneController@iclocreject');
    Route::get('/get-assessment-list', 'POneController@get_assessment_list');
    Route::post('/post-assessment-reject', 'POneController@post_assessment_reject');
    


    //Processor 2 
    Route::get('/loan_internal/calculation/{id}', 'PSecondController@loan_internal_cal_perone');
    //Route::post('/save/process6/{id}', 'LoanEliController@process6'); //hidden hitungan dsr
    Route::post('/save/process6/{id}', 'PSecondController@post_loan_cal_p2');
    Route::get('/pdfbatchheader/{id}', 'LoanEliController@pdfbatchheader');
    Route::get('/processor2/loancal/{id}', 'PSecondController@loan_cal');
    Route::get('/recount/loan/{id}', 'PSecondController@post_tenus_p2');
    Route::get('/cek/loan/{id}', 'PSecondController@cek_loan');
    Route::post('/recount/loan/{id}', 'PSecondController@post_tenus_p2');
    Route::get('/processor2/recount/{id}', 'PSecondController@loan_cal');
    Route::get('/processor2/{id}/step1', 'PSecondController@step1');
    Route::get('/pending_doc_pro2', 'PSecondController@pending_doc_pro2');
    Route::get('/doc-check', 'PSecondController@doc_check');
    Route::get('/call', 'PSecondController@call_103');
    Route::get('/docincomplete/p2', 'PSecondController@doc_incomplete');
    Route::get('/detail_processor2/{id}', 'PSecondController@detail');
    Route::get('/personal_financing/{id}', 'PSecondController@personal_financing');
    Route::get('/check-loan-cal-p2', 'PSecondController@pending_doc_pro2');
    Route::post('/cektenus-post', 'PSecondController@cektenus_post');

    Route::get('/cektenus_p2/{id}', 'PSecondController@cek_tenus');
    Route::post('/cektenus/post', 'PSecondController@resulttenus');
    Route::get('/batch-to-mbsb-process-2', 'PSecondController@batch_to_mbsb');
    Route::post('/submission_list', 'PSecondController@submission_list');
    Route::get('/get-submission-list', 'PSecondController@get_submission_list');

    

    
    
    //Route::post('/p2/custtenus/result', 'PSecondController@post_tenus_p2');
    Route::get('/p2/custtenus/result/{id}', 'PSecondController@post_tenus_p2');
    Route::post('/p2/custtenus/update/{id}', 'PSecondController@updates');

    //Route::post('/tenos/custtenus/store', 'LoanEliController@post_tenus_step1');
    //Route::post('/tenos/custtenus/store_step1', 'PSecondController@post_tenus_step1');
   
    
    //Processor 3 
    Route::post('/save/process7/{id}', 'LoanEliController@process7');
    Route::post('/save/process8/{id}', 'LoanEliController@process8');
    Route::get('/update-approval', 'PThreeController@update_approval');
    Route::get('/update-approval_perone/{id}', 'PThreeController@update_approval_perone');
    Route::post('/approval-approve/{id}', 'PThreeController@approval_approve');
    Route::get('/approval-reject/{id}', 'PThreeController@approval_reject');
    Route::post('/add-doc-pro3/{id}', 'PThreeController@adddocprocess11');
    Route::get('/approve-fix', 'PThreeController@approve_fix');
    Route::get('/reject-fix', 'PThreeController@reject_fix');
    Route::get('/add-doc-from-mbsb', 'PThreeController@add_doc');
    Route::get('/report/month', 'PThreeController@report_monthly');
    Route::get('/report_monthly', 'ReportManagerController@report_processor4');
    Route::post('report_monthly', 'PThreeController@report_monthly_view');
    Route::get('/additional_confirm/{id}', 'PThreeController@additional_confirm');
    Route::get('/upload/amount', 'PThreeController@upload_get');
    Route::post('/upload/amount/post', 'PThreeController@upload_amount');
    Route::post('/additional-doc-p3/{id}', 'PThreeController@additional_doc');
    Route::get('/additional_confirm/{id}', 'PThreeController@confirm_add_received');
    Route::post('/post-reject', 'PThreeController@post_reject');
    

    

    //Processor 4
    Route::get('/loan-eli/process11', 'LoanEliController@process11');
    Route::get('/report_monthly', 'ReportManagerController@report_processor4');
    Route::get('/appdisbursement/{id}', 'LoanEliController@disbursement');
    Route::get('/rejectdisbursement/{id}', 'LoanEliController@rejectdisbursement');
    Route::post('/adddocprocess11/{id}', 'LoanEliController@adddocprocess11');

    
    //Management
    Route::resource('file-manager', 'FileManagerController');
    Route::resource('list-folder', 'ListFolderController');
    Route::resource('document-folder', 'DocumentFolderController');
    
    Route::get('/folder-name', 'FileManagerController@get_folder_name');
    Route::get('/detail-folder', 'FileManagerController@detail_folder');
    Route::get('/filemanager/{id}', 'FileManagerController@detail_file');

resources/views/adminpage/file_manage1/edit.blade.php
@extends('vadmin.tampilan')

@section('content')

	<!-- Bootstrap Material Datetime Picker Css -->
    <link href="{{asset('admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet" />

	<section class="content">
        <div class="container-fluid">
            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="{{route('announc.index')}}"><i class="material-icons">folder_open</i> File Manager</a></li>
                        <li class="active"><i class="material-icons">create</i> Edit</li>

                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>Edit</h2>
                        </div>

                        <div class="body">
                            <div class="row clearfix">
                                
                                {!! Form::model($file, ['method' => 'PUT','files' => true, 'route' => ['file-manager.update',  $file->id ] ]) !!}
                                    
                                    @include('adminpage.file_manager.form')
                                     

                                    <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                    
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>

        </div>
    </section>

	<!-- Jquery Core Js -->
    <script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{asset('admin/js/pages/forms/basic-form-elements.js')}}"></script>

    
@endsection()

resources/views/adminpage/file_manage1/embed.blade.php
<embed src="attach/{{$announc->attach}}" type="application/pdf"   height="300px" width="100%" class="responsive">
<a href="study/sample.pdf">download</a>

resources/views/adminpage/file_manage1/form.blade.php
<div class="col-sm-12">
    <h5>Title :</h5>
    <div class="form-group form-float @if ($errors->has('title')) has-error @endif">
        <div class="form-line">
            
            {!! Form::label('title', 'Title ', ['class' => 'form-label']) !!}
            {!! Form::text('title', null, ['class' => 'form-control']) !!}
            @if ($errors->has('title')) <p class="help-block">{{ $errors->first('title') }}</p> @endif
            
        </div>
    </div>
</div>

<div class="col-md-12">
    <h5>Desc :</h5>
    <div class="form-group @if ($errors->has('desc')) has-error @endif">
        {!! Form::textarea('desc', null, ['class' => 'form-control ckeditor', 'id' => 'desc']) !!}
        @if ($errors->has('desc')) <p class="help-block">{{ $errors->first('desc') }}</p> @endif
    </div>
</div>



<div class="col-sm-6">
    <h5>Attachment:</h5>
    <div class="form-group form-float @if ($errors->has('attach')) has-error @endif">
            
        {!! Form::file('attach', null, ['class' => 'form-control']) !!}
        @if ($errors->has('attach')) <p class="help-block">{{ $errors->first('attach') }}</p> @endif
            
    </div>
</div>

<div class="col-md-6">
    <div class="form-group form-float @if ($errors->has('status')) has-error @endif">
        <h5>Status</h5>
        <div class="">
            {!! Form::select('status', array('1' => 'Activ', '0' => 'Non Activ'), '1'); !!}
        </div>
        @if ($errors->has('status')) <p class="help-block">{{ $errors->first('status') }}</p> @endif
    </div>  
</div>


@push('scripts')
<script src="//cdn.ckeditor.com/4.6.2/standard/ckeditor.js"></script>

<script type="text/javascript">  
    CKEDITOR.replace( 'desc', { 
    shiftEnterMode : CKEDITOR.ENTER_P,
    enterMode: CKEDITOR.ENTER_BR, 
    on: {'instanceReady': function (evt) { evt.editor.execCommand('');     }},
    });      
</script>

@endpush

resources/views/adminpage/file_manage1/index.blade.php
@extends('vadmin.tampilan')

@section('content')

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css">
    

    <section class="content">
        <div class="container-fluid">
            <div class="row clearfix"><!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li class="active"><a href="{{route('file-manager.index')}}"><i class="material-icons">folder_open</i> File Manager</a></li>
                    </ol>
                </div>
            </div><!-- End of breadcrumber -->

            <!-- Notification -->
            <div class="row clearfix">
                @if ($message = Session::get('success')) 
                <div class="alert bg-green alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('delete'))
                <div class="alert bg-pink alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('update'))
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @endif
            </div>
            <!-- End of Notif -->

            <div class="row clearfix demo-button-sizes"><!-- Button tambah -->
                <div class="col-md-10"></div>                
                <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                    <a href="{{ route('file-manager.create') }}" type="submit" class="btn btn-success btn-block btn-lg waves-effect" style="cursor:pointer;">
                      Add
                    </a>
                </div>
            </div> <!-- End of button tambah -->
           
            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>File Manager</h2>
                        </div>
                        <div class="body">
                            <table class="table" id="example">
                                <thead> 
                                    <tr>
                                        <th width="5%">#</th>
                                        <th width="20%">Title</th>
                                        <th width="40%">Desc</th>
                                        <th width="10%">Attach</th>
                                        <th width="20%">Status</th>
                                        <th>Action</th>             
                                    </tr>
                                </thead>
                                <tbody>
                                	<?php $i = 1; ?>

                                	@foreach($file as $data)
                                	<tr>
                                		<td>{{$i++}}</td>
                                		<td>{{$data->title}}</td>
                                		<td>{{$data->desc}}</td>
                                		<td>
                                            @if($data->attach == "NULL")
                                                {{$data->attach}}
                                            @else
                                                <a href="filemanager/{{$data->attach}}" class='btn btn-warning' target="_blank">{{$data->attach}}</a>
                                            @endif
                                        </td>
                                        <td>
                                            <div class="switch">
                                                @if($data->status == 0)
                                                <label>Non Act<a href="{{url('/file-manager/update1/'.$data->id)}}" class="lever switch-col-red" onclick="alert('The File Manager will be active!');"></a>Active</label>
                                                @else
                                                <label>Non Act<a href="{{url('/file-manager/update0/'.$data->id)}}" onclick="alert('The File Manager will be non active!');">
                                                    <input type="checkbox" id="aksi" name="status" checked><span class="lever switch-col-red"></span></a>Active</label>
                                                @endif
                                            </div>
                                        </td>
                                        <td>
                                            @include('shared._actions', [
                                                'entity' => 'file-manager',
                                                'id' => $data->id
                                            ])
                                        </td>
                                	</tr>
                                	
                                	@endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
	
	<script>
	    $(document).ready(function() {
	    $('#example').DataTable();
	    });
	</script>

	<script>
	    $(document).ready(function() {
	    $('#example1').DataTable( {
	        dom: 'Bfrtip',
	        buttons: [
	            'copyHtml5',
	            'excelHtml5',
	            'csvHtml5',
	            'pdfHtml5'
	        ]
	    } );
	} );
	</script>

    
@endsection

resources/views/adminpage/file_manage1/new.blade.php
@extends('vadmin.tampilan')

@section('content')

	<!-- Bootstrap Material Datetime Picker Css -->
    <link href="{{asset('admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet" />

	<section class="content">
        <div class="container-fluid">
            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="{{route('announc.index')}}"><i class="material-icons">folder_open</i> File Manager</a></li>
                        <li class="active"><i class="material-icons">create</i> Add</li>

                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>Add</h2>
                        </div>

                        <div class="body">
                            <div class="row clearfix">
                                {!! Form::open(['route' => ['file-manager.store'], 'enctype' => "multipart/form-data" ]) !!}
                                    
                                    @include('adminpage.file_manager.form')

                                    <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                    
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>

        </div>
    </section>

	<!-- Jquery Core Js -->
    <script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Custom Js -->
    <script src="{{asset('admin/js/pages/forms/basic-form-elements.js')}}"></script>

    
@endsection()

resources/views/adminpage/file_manage1/show.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">
            <div class="row clearfix"><!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li class="active"><a href="{{route('announc.index')}}"><i class="material-icons">mic</i> Announcement</a></li>
                    </ol>
                </div>
            </div><!-- End of breadcrumber -->

            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>Announcment</h2>
                        </div>
                        <div class="body">
                        	<div class="row">
                        		
                        		<div class="col-md-8">
                        			 
	                        		<h2>{{$announc->title}}</h2>
	                        	
	                                <p>{{$announc->desc}}</p>
		                            <blockquote>
		                                <footer>{{$announc->user->name}} 
		                                
		                                <p><cite title="Source Title"> {{ $announc->created_at->toFormattedDateString() }}</cite></p>
		                                </footer>
		                            </blockquote>
		                            	
		                                <a href="{{url('/')}}/attach/{{$announc->attach}}" class='btn btn-warning' target="_blank" style="margin-top: 30px">{{$announc->attach}}</a>

		                                
	                        	</div>

	                        	

	                            <div class="col-md-4">
		                            		
	                        		<ul>
	                        			@foreach ($other as $data)

	                        			<li style="color:red"><a href="{{url('/announc/show/'.$data->id)}}" style="color: red; text-decoration: none">{{ $announc->created_at->toFormattedDateString() }}-- {{$data->title}}</a></li>

	                        			@endforeach
	                        		</ul>
		                            		
	                            </div>
                        	</div>

                            
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>    

@endsection