routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    //return view('welcome');
    return view('utama.main');
});*/

Route::get('/test', function () {
    
    return view('adminpage.message.template_reply');
});

Route::get('/step', function () {
    
    return view('mo.test');
});

Route::get('/step2', function () {
    
    return view('mo.test2');
});

Route::get('/', 'Utama\UtamaController@index');
Route::post('praaplication/store', 'Praaplication\PraaplicationController@store');
Route::get('praapplication/{id}', 'Praaplication\PraaplicationController@kira');
Route::post('praapplication/just_calculate', 'Praaplication\PraaplicationController@just_calculate');

Route::resource('cif', 'CifController');

Route::get('/hidden', 'Utama\UtamaController@hidden');

Route::get('about', 'Utama\UtamaController@about');
Route::get('service', 'Utama\UtamaController@service');
Route::get('faq', 'Utama\UtamaController@faq');
Route::get('contact', 'Utama\UtamaController@contact');
//Route::post('/praaplication/save', 'Praaplication\PraaplicationController@save_praaplication');

Route::resource('message', 'Utama\MessageController');
Route::get('/reply-que/{id}', 'Utama\MessageController@show');
Route::post('/reply_post', 'Utama\MessageController@update');

Route::resource('praaplication', 'Praaplication\PraaplicationController');

Route::post('/praaplication/kelayakan', 'Praaplication\PraaplicationController@kelayakan');
Route::get('/praaplication/upload-file/{id}', 'Praaplication\PraaplicationController@upload');
Route::post('/praaplication/upload-file/uploads/{id}', 'Praaplication\PraaplicationController@uploads');
Route::post('/praaplication/finish', 'Praaplication\PraaplicationController@finish');
Route::get('upload-praaplication', 'Praaplication\PraaplicationController@upload');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/adminnew', 'AdminNewController@index')->name('adminnew');


Route::group( ['middleware' => ['auth']], function() {

    Route::resource('test', 'TestController');
    Route::resource('mo', 'MOController');
    Route::get('/add_leader/{id}', 'MOController@add_leader');
    Route::post('/mo/add_leader', 'MOController@post_leader'); 
    Route::get('/mo/update1/{id}', 'MOController@updatestatus1'); 
    Route::get('/mo/update2/{id}', 'MOController@updatestatus2');
    Route::get('/add_manager/{id}', 'MOController@add_manager');
    Route::post('/mo/add_manager', 'MOController@post_manager'); 
    

    Route::resource('users', 'UserController');
    Route::get('/users/edit/{id}', 'UserController@edit');
    Route::delete('/users/destroy/{id}', 'UserController@destroy');
    Route::resource('stage', 'StageController');
    Route::resource('profile1', 'ProfileController');
    Route::post('/save/profile/{id}', 'ProfileController@store_profile');
    Route::post('/save/background/{id}', 'ProfileController@store_background');
    Route::resource('cus_mo', 'CustomerMoController');
    
    Route::post('/profileupdate', 'ProfileController@update');
    

    Route::get('/userdata/update/{id}', 'UserController@updatestatus'); 
    Route::get('/userdata/update1/{id}', 'UserController@updatestatus1'); 
    Route::post('/users/status/{id}', 'UserController@status'); //tes
    
    Route::resource('roles', 'RoleController');
    Route::resource('loan', 'LoanController');
    
    Route::get('/location/show/{id}', 'AdminNewController@view_location');
    Route::get('/history/show/{id}', 'AdminNewController@view_history');
    Route::get('/doc/show/{cus_id}', 'AdminNewController@view_doc');
    Route::get('/doc/submit/{id}', 'AdminNewController@submit_doc_cus');
    Route::post('/doc/submit/uploads/{id}', 'AdminNewController@uploads');

    //view form
    Route::get('/view_form/{id}/first_step', 'ViewController@first_step');
    Route::get('/view_form/{id}/second_step', 'ViewController@second_step');
    Route::get('/view_form/{id}/fourth_step', 'ViewController@fourth_step');

    //Processor 1
    Route::get('/assess_addcus_X', 'AssessmentController@create'); //hidden add cus lama
    Route::get('/assess_addcus', 'POneController@create');
    Route::post('/processor1/addcus', 'POneController@store');
    Route::get('/cus/add/{id}', 'PMOController@form_upload');
    Route::get('/doc/spekar/{id}', 'AdminNewController@submit_verify');
    Route::get('/speakar/doc/{id}', 'AssessmentController@kira');
    Route::post('/oassessment/kira/uploads/{id}', 'AssessmentController@uploads');
    Route::post('/save/spekar/{id}', 'LoanEliController@store');
    Route::get('/doc/spekardown/{cus_id}', 'LoanEliController@show');
    Route::post('/routeto/user/{id}', 'LoanEliController@routeto');
    Route::post('/send_spekar', 'LoanEliController@spekar_routeto');
    Route::get('/uploadspekar_p1', 'POneController@uploadspekar_p1');
    Route::get('/route_to_mo', 'POneController@route_to_mo');
    Route::post('/iclocreject/{id}', 'POneController@iclocreject');
    Route::get('/get-assessment-list', 'POneController@get_assessment_list');
    Route::post('/post-assessment-reject', 'POneController@post_assessment_reject');
    


    //Processor 2 
    Route::get('/loan_internal/calculation/{id}', 'PSecondController@loan_internal_cal_perone');
    //Route::post('/save/process6/{id}', 'LoanEliController@process6'); //hidden hitungan dsr
    Route::post('/save/process6/{id}', 'PSecondController@post_loan_cal_p2');
    Route::get('/pdfbatchheader/{id}', 'LoanEliController@pdfbatchheader');
    Route::get('/processor2/loancal/{id}', 'PSecondController@loan_cal');
    Route::get('/recount/loan/{id}', 'PSecondController@post_tenus_p2');
    Route::get('/cek/loan/{id}', 'PSecondController@cek_loan');
    Route::post('/recount/loan/{id}', 'PSecondController@post_tenus_p2');
    Route::get('/processor2/recount/{id}', 'PSecondController@loan_cal');
    Route::get('/processor2/{id}/step1', 'PSecondController@step1');
    Route::get('/pending_doc_pro2', 'PSecondController@pending_doc_pro2');
    Route::get('/doc-check', 'PSecondController@doc_check');
    Route::get('/call', 'PSecondController@call_103');
    Route::get('/docincomplete/p2', 'PSecondController@doc_incomplete');
    Route::get('/detail_processor2/{id}', 'PSecondController@detail');
    Route::get('/personal_financing/{id}', 'PSecondController@personal_financing');
    Route::get('/check-loan-cal-p2', 'PSecondController@pending_doc_pro2');
    Route::post('/cektenus-post', 'PSecondController@cektenus_post');

    Route::get('/cektenus_p2/{id}', 'PSecondController@cek_tenus');
    Route::post('/cektenus/post', 'PSecondController@resulttenus');
    Route::get('/batch-to-mbsb-process-2', 'PSecondController@batch_to_mbsb');
    Route::post('/submission_list', 'PSecondController@submission_list');
    Route::get('/get-submission-list', 'PSecondController@get_submission_list');

    

    
    
    //Route::post('/p2/custtenus/result', 'PSecondController@post_tenus_p2');
    Route::get('/p2/custtenus/result/{id}', 'PSecondController@post_tenus_p2');
    Route::post('/p2/custtenus/update/{id}', 'PSecondController@updates');

    //Route::post('/tenos/custtenus/store', 'LoanEliController@post_tenus_step1');
    //Route::post('/tenos/custtenus/store_step1', 'PSecondController@post_tenus_step1');
   
    
    //Processor 3 
    Route::post('/save/process7/{id}', 'LoanEliController@process7');
    Route::post('/save/process8/{id}', 'LoanEliController@process8');
    Route::get('/update-approval', 'PThreeController@update_approval');
    Route::get('/update-approval_perone/{id}', 'PThreeController@update_approval_perone');
    Route::post('/approval-approve/{id}', 'PThreeController@approval_approve');
    Route::get('/approval-reject/{id}', 'PThreeController@approval_reject');
    Route::post('/add-doc-pro3/{id}', 'PThreeController@adddocprocess11');
    Route::get('/approve-fix', 'PThreeController@approve_fix');
    Route::get('/reject-fix', 'PThreeController@reject_fix');
    Route::get('/add-doc-from-mbsb', 'PThreeController@add_doc');
    Route::get('/report/month', 'PThreeController@report_monthly');
    Route::get('/report_monthly', 'ReportManagerController@report_processor4');
    Route::post('report_monthly', 'PThreeController@report_monthly_view');
    Route::get('/additional_confirm/{id}', 'PThreeController@additional_confirm');
    Route::get('/upload/amount', 'PThreeController@upload_get');
    Route::post('/upload/amount/post', 'PThreeController@upload_amount');
    Route::post('/additional-doc-p3/{id}', 'PThreeController@additional_doc');
    Route::get('/additional_confirm/{id}', 'PThreeController@confirm_add_received');
    Route::post('/post-reject', 'PThreeController@post_reject');
    

    

    //Processor 4
    Route::get('/loan-eli/process11', 'LoanEliController@process11');
    Route::get('/report_monthly', 'ReportManagerController@report_processor4');
    Route::get('/appdisbursement/{id}', 'LoanEliController@disbursement');
    Route::get('/rejectdisbursement/{id}', 'LoanEliController@rejectdisbursement');
    Route::post('/adddocprocess11/{id}', 'LoanEliController@adddocprocess11');

    
    //Management
    Route::resource('file-manager', 'FileManagerController');
    Route::resource('list-folder', 'ListFolderController');
    Route::resource('document-folder', 'DocumentFolderController');
    
    Route::get('/folder-name', 'FileManagerController@get_folder_name');
    Route::get('/detail-folder', 'FileManagerController@detail_folder');
    Route::get('/filemanager/{id}', 'FileManagerController@detail_file');

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use App\Manager;
use App\Permission;
use App\Authorizable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    //use Authorizable;

    
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        

        $result = User::latest()->where('email','<>', 'wakudiallah05@gmail.com')->orderBy('id', 'DESC')->paginate();
        
        /*$result = User::latest()
            ->with('users') //bring along details of the friend
            ->join('model_has_roles', 'model_has_roles.model_id', '=', 'users.id')
            ->get(); // exclude extra details from friends table*/

            /*$result = User::join('model_has_roles', 'users.id', '=', 'model_has_roles.model_id')
    ->select('users.id', 'contacts.phone', 'orders.price')
    ->where('model_has_roles.model_id', '<>', '')
    ->get();*/


        return view('adminpage.user.index', compact('result'));
    }

    public function status(Request $request , $id)
    {
        $st         = User::find($id);
        $st->status = $request->status;
        $st->save();

        return view('adminpage.user.index')->with(['update' => 'User data successfully updated']);
    }


    public function updatestatus(Request $request , $id)
    {
        $st         = User::find($id);
        $st->status = '1';
        $st->save();

        return redirect('users')->with(['update' => 'User data successfully updated']);
    }

    public function updatestatus1(Request $request , $id)
    {
        $st = User::find($id);
        $st->status = '0';
        $st->save();

        return redirect('users')->with(['update' => 'User data successfully updated']);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$roles = Role::pluck('name', 'id');
        $roles = Role::where('id', '!=', 3)->pluck('name', 'id');

        return view('adminpage.user.new', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'roles' => 'required|min:1',
            'status' => 'required'
        ]);

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ( $user = User::create($request->except('roles', 'permissions')) ) {

            $this->syncPermissions($request, $user);

            flash('User has been created.');

        } else {
            flash()->error('Unable to create user.');
        }

        return redirect()->route('users.index')->with(['success' => 'User data saved successfully']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $user = User::find($id);
        $roles = Role::pluck('name', 'id');
        $permissions = Permission::all('name', 'id');

        return view('adminpage.user.edit', compact('user', 'roles', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'roles' => 'required|min:1'
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        // Handle the user roles
        $this->syncPermissions($request, $user);

        $user->save();

        return redirect()->route('users.index')->with(['update' => 'User data successfully updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @internal param Request $request
     */
    public function destroy($id)
    {
        if ( Auth::user()->id == $id ) {
            flash()->warning('Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if( User::findOrFail($id)->delete() ) {
            flash()->success('User has been deleted');
        } else {
            flash()->success('User not deleted');
        }

        return redirect('users')->with(['delete' => 'User data successfully deleted']);
    }

    /**
     * Sync roles and permissions
     *
     * @param Request $request
     * @param $user
     * @return string
     */
    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);

        return $user;
    }
}

resources/views/adminpage/user/mo/edit.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">

            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="{{route('mo.index')}}"><i class="material-icons">person</i> User</a></li>
                        <li class="active"><i class="material-icons">person_add</i>MO User</li>
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

		    <div class="row clearfix">
		        <div class="col-lg-12">
		        	<div class="card">
		        		<div class="header bg-red">Add</div>
		        		<div class="body">
				            
                            {!! Form::model($mo, ['method' => 'PUT', 'route' => ['mo.update', $mo->id] ]) !!}

				            	@include('adminpage.user.mo.form')
				                
				                <!-- Submit Form Button -->
				                <div class="row clearfix">
                                	<div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                </div>
				            {!! Form::close() !!}
			            </div>
		            </div>
		        </div>
		    </div>
        </div>
    </section>

@endsection

resources/views/adminpage/user/mo/form.blade.php
<!-- Name Form Input -->
<div class="form-group form-float @if ($errors->has('name')) has-error @endif">
    <div class="form-line">
        {!! Form::label('name', 'Name') !!}
        {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
    </div>
    @if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
</div>

<!-- email Form Input -->
<div class="form-group form-float @if ($errors->has('email')) has-error @endif">
    <div class="form-line">
        {!! Form::label('email', 'Email') !!}
        {!! Form::text('email', null, ['class' => 'form-control', 'placeholder' => 'Email']) !!}
    </div>
    @if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
</div>

<!-- password Form Input -->
<div class="form-group form-float @if ($errors->has('password')) has-error @endif">
    <div class="form-line">
        {!! Form::label('password', 'Password') !!}
        {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) !!}
    </div>
    @if ($errors->has('password')) <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>

<!-- Roles Form Input -->

<input type="text" name="roles" value="3" class="hidden">




<!-- <div class="form-group form-float @if ($errors->has('status_head')) has-error @endif">
    <div class="form-line">

        {!! Form::label('head','Leader / Follower') !!}
        {!! Form::select('status_head',[1=>'Leader',0=>'Follower'],null,['class'=>'form-control']) !!}
        
    </div>
    @if ($errors->has('status_head')) <p class="help-block">{{ $errors->first('status_head') }}</p> @endif
</div> -->

<div class="form-group form-float @if ($errors->has('team_leader')) has-error @endif">
    <div class="form-line">
        {!! Form::label('leader','Team Leader') !!}
        
        <select class="form-control show-tick js-example-basic-single js-states" data-live-search="true" name="leader" id="one" required>                                
            @foreach($team_leader as $data)
                <option value="{{$data->id}}">{{$data->name}} </option>
            @endforeach
        </select>
    </div>
    @if ($errors->has('team_leader')) <p class="help-block">{{ $errors->first('team_leader') }}</p> @endif
</div>


<div class="form-group form-float @if ($errors->has('manager')) has-error @endif">
    <div class="form-line">
        {!! Form::label('manager','Manager') !!}
        
        <select class="form-control show-tick js-example-basic-single js-states" data-live-search="true" name="manager" id="one" required>                                
            @foreach($manager as $data) 
                <option value="{{ $data->id }}"> {{ $data->name }}</option>
            @endforeach
        </select>
    </div>
    @if ($errors->has('manager')) <p class="help-block">{{ $errors->first('manager') }}</p> @endif
</div>


<div class="form-group form-float @if ($errors->has('status')) has-error @endif">
    <div class="form-line">
        {!! Form::label('status','Status') !!}
        {!! Form::select('status',[1=>'Active',0=>'Non Active'],null,['class'=>'form-control']) !!}
    </div>
    @if ($errors->has('status')) <p class="help-block">{{ $errors->first('status') }}</p> @endif
</div>


<!-- <input type="text" name="status" value="1" class="hidden"> -->

<!-- Permissions -->
@if(isset($user))
    @include('shared._permissions', ['closed' => 'true', 'model' => $user ])
@endif

resources/views/adminpage/user/mo/index.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">

            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="javascript:void(0);"><i class="material-icons">person</i> User MO</a></li>
                        
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

            <!-- Notification -->
            <div class="row clearfix">
                @if ($message = Session::get('success')) 
                <div class="alert bg-green alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('delete'))
                <div class="alert bg-pink alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('update'))
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @endif
            </div>
            <!-- End of Notif -->

            <div class="row clearfix demo-button-sizes">
                <div class="col-md-10"></div>
                @can('add_users')
                <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                    <a href="{{ route('mo.create') }}" type="submit" class="btn btn-success btn-block btn-lg waves-effect" style="cursor:pointer;">
                      Add
                    </a>
                </div>
                @endcan
            </div>

		    <div class="row clearfix">
                <div class="card">
                    <div class="header bg-red">
                        <h2>Data MO -- </h2>
                    </div>
                    <div class="body">
                        <table class="table" id="example">
                        	<thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
					                <th>Name</th>
					                <th>Email</th>
					                <th>Leader</th>
                                    <th>Manager</th>
                                    <th>Workgroup</th>
					                <th>Status</th>
					                <th class="text-center">Actions</th>          
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1; ?>

                            	@foreach($result as $item)
                                @if(($item->model->role->id == 3)  || ($item->model->role->id == 12))
				                <tr>
				                    <td>{{$i++}}</td>
                                    <td>US{{ $item->id }}</td>
				                    <td>{{ $item->name }}</td>
				                    <td>{{ $item->email }}</td>
				                    
				                    <td>
										@if($item->model->role->id == 5)
                                        @else
                                            @if(empty($item->leader) )
                                            <a href="{{url('/add_leader/'.$item->id)}}" class="btn btn-primary"><i class="material-icons disabled">person</i> Add Leader </a>
                                            @elseif(!empty($item->leader) )
                                                <span class="btn btn-danger">{{$item->nama_leader->name}}</span>
                                            @else
                                                <span class="label bg-white">Follower</span>
                                            @endif
                                        @endif
				                    </td>
                                    <td>

                                        @if(empty($item->manager))
                                        <a href="{{url('/add_manager/'.$item->id)}}" class="btn btn-primary"><i class="material-icons disabled">person</i> Add Manager </a>
                                        @else
                                            <span class="btn btn-danger">{{$item->nama_manager->name}}</span>
                                        @endif
                                    </td>
                                    <td>
                                        {{ $item->roles->implode('name', ', ') }}
                                    </td>
				                    <td>
                                        <div class="switch">  <!-- update status ini belum -->
                                            @if($item->status == 0)
                                            <label>Non Act<a href="{{url('/mo/update1/'.$item->id)}}" class="lever switch-col-red" onclick="alert('User MO akan di aktif!');"></a>Active</label>
                                            @else
                                            <label>Non Act<a href="{{url('/mo/update2/'.$item->id)}}" onclick="alert('User MO akan di nonaktif!');">
                                                <input type="checkbox" id="aksi" name="status" checked><span class="lever switch-col-red"></span></a>Active</label>
                                            @endif
                                        </div>
	                            	</td>

				                    @can('edit_users')
				                    <td class="text-center">
				                        @include('shared._actions', [
				                            'entity' => 'mo',
				                            'id' => $item->id
				                        ])
				                    </td>
				                    @endcan
				                </tr>
                                @endif
				            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

		    
        </div>
    </section>
    

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>

    <script>
        $(document).ready(function() {
        $('#example').DataTable();
        });
    </script>

    <script type="text/javascript">
        
    </script>
    <!-- End status -->

@endsection

resources/views/adminpage/user/mo/new.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">

            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="{{route('mo.index')}}"><i class="material-icons">person</i> User MO</a></li>
                        <li class="active"><i class="material-icons">person_add</i>MO User</li>
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

		    <div class="row clearfix">
		        <div class="col-lg-12">
		        	<div class="card">
		        		<div class="header bg-red">Add</div>
		        		<div class="body">
				            {!! Form::open(['route' => ['mo.store'] ]) !!}
				            	@include('adminpage.user.mo.form')
				                
				                <!-- Submit Form Button -->
				                <div class="row clearfix">
                                	<div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                </div>
				            {!! Form::close() !!}
			            </div>
		            </div>
		        </div>
		    </div>
        </div>
    </section>

@endsection